default-members = ["crates/gpui-kit"]

[workspace]
resolver = "2"
members = [
    "crates/assets",
    "crates/gpui-kit",
    "crates/utils"
]

[workspace.dependencies]
gpui = { git = "https://github.com/zed-industries/zed.git", rev = "78098f6809346ba8b45db7ffa768fba75578a263" }
rust-embed = "8.2.0"
anyhow = "1.0.79"
